### ISSUE TITLE
[TASK] Create a bot for benchmark the DKG

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#331]
### Overview

We should create a new bot/cli/service that will be running and it is main goal is the following:

1. Connect to a running testnet with the DKG pallets deployed.
2. On every new block, we create a batch of Random Proposals.
3. Send these Proposals as a batch call to the DKG system.
4. Repeat.

### Configuration 

It should contain a small config file with the following:

```toml
node-url = "ws://localhost:9944"
suri = "...."
proposals-per-batch = 15
```
