### ISSUE TITLE
[TASK] Add a Start Block for syncing in Substrate configration

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#345]
### Overview

Right now relayers do start syncing on the substrate, they sync from block zero, which could take more time than needed. We need to add a configuration option to allow for custom starting block number, similar to what we are doing in the evm contracts `deployed_at` value.

### Example

```toml
[substrate.tangle]
name = "tangle"
http-endpoint = "http://localhost:9933"
ws-endpoint = "ws://localhost:9944"
chain-id = 1080
enabled = true
runtime = "DKG"
suri = "//Bob"
start-block = 1000 # if not provided, we start from the latest block.

[[substrate.tangle.pallets]]
pallet = "DKG"
events-watcher = { enabled = true, polling-interval = 3000, print-progress-interval = 30000 }

[[substrate.tangle.pallets]]
pallet = "DKGProposalHandler"
events-watcher = { enabled = true, polling-interval = 3000, print-progress-interval = 30000 }
```
