### ISSUE TITLE
[BUG] Got `InvalidExtData` Error When Submitting The Transaction On Substrate

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/relayer#549]
I've set up the local relayer with the Tangle network to test the transaction on Substrate.

When I made a withdrawal, **_it worked without the relayer_** and I could see my balance was updated. But when I select the local relayer to make a withdrawal on my behalf. I got an `InvalidExtData` error.

```
2023-06-29T08:44:19.069244Z ERROR webb_relayer_handlers: Error("Error while watching Tx: Runtime error: Module(ModuleError { pallet: \"VAnchorBn254\", error: \"InvalidExtData\", description: [], error_data: ModuleErrorData { pallet_index: 39, error: [6, 0, 0, 0] } })")
    at crates/relayer-handlers/src/lib.rs:119
```

### My setup

- https://github.com/webb-tools/relayer - `develop` branch (commit https://github.com/webb-tools/relayer/tree/cf0534ddef8e1b6d395f8b031ae7d9d836e620d7) and command that I used to run the local relayer
	- `cargo run --bin webb-relayer --features cli -- -c ./config/development/substrate-local -vvv --tmp` 
	  (I've updated the config file like this)

		```toml
		port = 9955
		
		[substrate.local]
		name = "tangle"
		chain-id = 1081
		enabled = true
		http-endpoint = "http://localhost:9933"
		ws-endpoint = "ws://localhost:9944"
		runtime = "WebbProtocol"
		suri = "//Alice//stash"
		
		[[substrate.local.pallets]]
		pallet = "VAnchorBn254"
		events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 6000 }
		```
- https://github.com/webb-tools/tangle `main` branch (commit https://github.com/webb-tools/tangle/tree/5c5aa2c72b2e326c618b58d52aeb48649c40b608) and the script that I used to run the local Tangle
	- `sh ./scripts/run-standalone.sh --clean`

### Screen Recording

https://github.com/webb-tools/relayer/assets/60747384/99e1dff7-fc39-4f0b-9248-e549cfd36b54
